### ISSUE TITLE
Not working with 47.1 on 10.13.2 (High Sierra)

### ISSUE THREAD

**Issue by pglevy** [AMoreaux/Sketch-Icons#19]
Just downloaded and installed the plug-in.

When I try Import, nothing comes up. Nothing seems to happen at all.

I tried disabling all other plug-ins, but that didn't have any effect.

**Comment by AMoreaux** [comment]
hi @pglevy can you send me the log please.
![image](https://user-images.githubusercontent.com/7237157/35119257-b12d5e8e-fc94-11e7-906d-52c62859d957.png)
![image](https://user-images.githubusercontent.com/7237157/35119268-b81cb276-fc94-11e7-9c5f-7a67f37ecaba.png)

**Comment by pglevy** [comment]
[Plugin Output.log](https://github.com/AMoreaux/Sketch-Icons/files/1644547/Plugin.Output.log)

**Comment by AMoreaux** [comment]
How do make to install the plugin ?

**Comment by pglevy** [comment]
Method 3 in the readme

**Comment by AMoreaux** [comment]
Your macos version is el capitan ?

**Comment by dumopuh** [comment]
Hi! I have the same situation.

macOS High Sierra v. 10.13.2

Installation methods (no difference):

— 2 (plugin v.3.0.12)
— 3 (plugin v.3.0.14) 

[Plugin Output.log](https://github.com/AMoreaux/Sketch-Icons/files/1652179/Plugin.Output.log)

**Comment by pglevy** [comment]
No... High Sierra.

**Comment by AMoreaux** [comment]
@dumopuh , @pglevy Can you tell me your email ? (my address is on my profile) I send you the last released (in beta) to try.

**Comment by jluna79** [comment]
Hi, just installed the plugin (High Sierra, using sketch runner).

When I try to import the icons I am getting a very weird behaviour: Icons are smashed into a solid colour square.
![screen shot 2018-01-23 at 19 29 18](https://user-images.githubusercontent.com/411374/35293373-c7007f6a-0073-11e8-9783-2c43497772ef.png)

I reviewed the output and foud that the problem is caused by a squared path that is added to the icon. 
![sketch-icons-bug](https://user-images.githubusercontent.com/411374/35293925-858d147e-0075-11e8-93ae-5f7dc24a9e7e.gif)

I have 100+ icons on this project so going one by one removing the Path is just impossible. Please help! :)

**Comment by AMoreaux** [comment]
@pglevy @dumopuh  It seems like it's a bug in high sierra and sketch 47. It will work with sketch 48

**Comment by pglevy** [comment]
Thanks for looking into it!
