### ISSUE TITLE
Can't find Symbols to add on color

### ISSUE THREAD

**Issue by andreechou** [AMoreaux/Sketch-Icons#33]
<img width="1600" alt="captura de tela 2018-03-05 19 08 29" src="https://user-images.githubusercontent.com/3429661/37002473-9ab7f6e0-20a8-11e8-84c4-89629d46dfd5.png">

Plugin can't find Symbols to add to Color.

**Comment by AMoreaux** [comment]
Hi, it will be fixed in the next release. 😉

**Comment by GabrielAtanasov** [comment]
@AMoreaux hi bro, you are fo really fantastic work with your plugin. You saved me an hour of dumb work, so I'm so thankful. But right now I must apply a mask to hundreds of icons, and I this feature of the plugin. Can you tell me when will be next release, because I need really fast to do these?

Thanks for support and keeping plugin up.

**Comment by GabrielAtanasov** [comment]
@valentinchrt @AMoreaux We are still waiting.

**Comment by AMoreaux** [comment]
@GabrielAtanasov You can try the beta version : https://www.dropbox.com/s/qmo8e1kq1ip6hvt/v4_sketch-icons_beta.zip?dl=0
