### ISSUE TITLE
Empty symbols when importing outlined icons

### ISSUE THREAD

**Issue by charlesbail** [AMoreaux/Sketch-Icons#4]
Hi there,
I'm trying to import the Feather icon sets. Icons are outlined, so it's only a path with a 2px border.
Once I import an icon with the Sketch-icons plugin, the symbol is empty.

I have no problem with a filled icon. I did the test myself with two icons I created: one with a fill and no border, the other with a border but no fill.

Sketch version: v48.2

Carl —

**Comment by valentinchrt** [comment]
Hey @charlesbail,

Thanks for your feedback! 
@AMoreaux is currently solving it :)

We'll let you know!

**Comment by valentinchrt** [comment]
Hey @charlesbail,

We have been working on it since yesterday, the outline icons are complicated to manage in Sketch. We have found a solution but it will take time to implement it. We will release a major version of Sketch Icons in the coming weeks that should solve the problem.

In the meantime, you can import all the icons using the fills with Sketch Icons :)

Also, you can download the Sketch Feather library here: https://dribbble.com/shots/4006413-Feather-Sketch-Library-200-Icons

(You will notice that they have also changed all strokes into fills).

**Comment by charlesbail** [comment]
Thanks for your time.

yes I saw the filled version from these icons, but this is why I used SketchIcons, because I wanted to imported stroke icons. I would have need this version because when scaling icons up (lets say from 24x24 to 32x32) I don't want to increase the width of the stroke, what will happend if it's a fill.

I'll just wait for the release, or do it one by one..!

Thanks again,
Charles —

**Comment by valentinchrt** [comment]
Ok I see.

For this case, do you want to apply a color mask as well? Or do you just want to import your icons?

**Comment by charlesbail** [comment]
For the stroked ones ? I already have a plugin to duplicate a color symbol over all my icons !

**Comment by valentinchrt** [comment]
We've just released 3.0.11. This version allows you to import stroke icons. 
Unfortunately, you can't apply a color mask on stroke icons.

We will release a major update soon (all about strokes / fills and color).

Thanks again @charlesbail ✌️
